name: ph
description: ph
dependencies:
  collection: any
  html: any
  petitparser: any
  source_maps: any
  source_span: any
dependency_overrides:
  html:
    path: /home/ryan/html
dev_dependencies:
  test: any
