name: protic
version: 0.1.3
description: Zero-effort HTML preprocessing/templating, with conditionals, includes, macros, and more
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/protic
dependencies:
  args: ^1.5.2
  collection: ^1.14.11
  html: ^0.14.0
  petitparser: ^2.4.0
  source_maps: ^0.10.8
  source_span: ^1.5.5
dev_dependencies:
  js: ^0.6.1
  node_preamble: ^1.4.6
  test: ^1.6.8
executables:
  protic:
environment:
  sdk: ">=2.0.0 <3.0.0"
