name: protic
version: 0.1.2
description: Zero-effort HTML preprocessing/templating, with conditionals, includes, macros, and more
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/protic
dependencies:
  args: ^1.4.4
  collection: ^1.14.11
  html: ^0.13.3
  petitparser: ^2.0.0
  source_maps: ^0.10.7
  source_span: ^1.4.1
dev_dependencies:
  js: ^0.6.1
  node_preamble: ^1.4.4
  test: ^1.3.0
executables:
  protic:
environment:
  sdk: ">=2.0.0 <3.0.0"
